#!/usr/bin/env python3
"""
Scan adventures/videos/ and write a starter manifest.

    python3 import-videos.py

Groups clips shot on the same day into one adventure, guesses a date for each
from (in order) the filename, the file's embedded creation time if ffprobe is
around, and finally the file's modified time. Writes adventures.generated.js —
rename the entries, add your notes, then paste them into adventures.js.

Nothing is overwritten: adventures.js is never touched by this script.
"""

import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
VIDEO_DIR = os.path.join(HERE, "videos")
OUT = os.path.join(HERE, "adventures.generated.js")

PLAYABLE = {".mp4", ".m4v", ".webm", ".ogv"}
NEEDS_CHECK = {".mov"}            # often fine, but iPhone HEVC is not
NEEDS_CONVERT = {".avi", ".wmv", ".mkv", ".flv", ".3gp", ".mpg", ".mpeg"}
VIDEO_EXTS = PLAYABLE | NEEDS_CHECK | NEEDS_CONVERT

# 20240803_142530 / 2024-08-03 / 2024_08_03 anywhere in the name
DATE_IN_NAME = re.compile(r"(20\d{2})[-_]?(0[1-9]|1[0-2])[-_]?(0[1-9]|[12]\d|3[01])")


def date_from_name(name):
    m = DATE_IN_NAME.search(name)
    if not m:
        return None
    return "%s-%s-%s" % m.groups()


def date_from_metadata(path):
    """Embedded creation time, if ffprobe is installed."""
    if not shutil.which("ffprobe"):
        return None
    try:
        out = subprocess.run(
            ["ffprobe", "-v", "quiet", "-print_format", "json",
             "-show_format", path],
            capture_output=True, text=True, timeout=20,
        )
        tags = json.loads(out.stdout or "{}").get("format", {}).get("tags", {})
        for key in ("creation_time", "com.apple.quicktime.creationdate"):
            if key in tags:
                return tags[key][:10]
    except Exception:
        pass
    return None


def date_from_mtime(path):
    return datetime.fromtimestamp(os.path.getmtime(path)).strftime("%Y-%m-%d")


def codec_of(path):
    if not shutil.which("ffprobe"):
        return None
    try:
        out = subprocess.run(
            ["ffprobe", "-v", "quiet", "-select_streams", "v:0",
             "-show_entries", "stream=codec_name", "-of", "csv=p=0", path],
            capture_output=True, text=True, timeout=20,
        )
        return out.stdout.strip() or None
    except Exception:
        return None


def slugify(s):
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", s.lower())).strip("-")


def pretty_day(iso):
    d = datetime.strptime(iso, "%Y-%m-%d")
    return d.strftime("%B %-d, %Y") if os.name != "nt" else d.strftime("%B %d, %Y")


def main():
    if not os.path.isdir(VIDEO_DIR):
        sys.exit("No videos/ directory next to this script.")

    files = sorted(
        f for f in os.listdir(VIDEO_DIR)
        if os.path.splitext(f)[1].lower() in VIDEO_EXTS
        and not f.startswith(".")
    )
    if not files:
        sys.exit("No video files found in %s" % VIDEO_DIR)

    days = {}
    warnings = []

    for name in files:
        path = os.path.join(VIDEO_DIR, name)
        ext = os.path.splitext(name)[1].lower()

        date = (date_from_name(name)
                or date_from_metadata(path)
                or date_from_mtime(path))
        days.setdefault(date, []).append(name)

        if ext in NEEDS_CONVERT:
            warnings.append((name, "browsers can't play %s" % ext))
        elif ext in NEEDS_CHECK:
            codec = codec_of(path)
            if codec in ("hevc", "h265"):
                warnings.append((name, "HEVC .mov — Chrome and Firefox won't play it"))
            elif codec is None:
                warnings.append((name, ".mov — plays in Safari, check Chrome"))

    lines = [
        "/* Generated by import-videos.py — %d clips across %d days."
        % (len(files), len(days)),
        "   Rename the titles, write the notes, then move these into",
        "   adventures.js. This file is not loaded by the page. */",
        "",
        "window.ADVENTURES = [",
        "",
    ]

    for date in sorted(days, reverse=True):
        clips = sorted(days[date])
        src = ("[\n      " +
               ",\n      ".join('"videos/%s"' % c for c in clips) +
               "\n    ]") if len(clips) > 1 else '"videos/%s"' % clips[0]
        lines += [
            "  {",
            '    id: "%s",' % slugify(date),
            '    title: "%s",' % pretty_day(date),
            '    date: "%s",' % date,
            '    place: "",',
            "    tags: [],",
            '    note: "",',
            "    src: %s" % src,
            "  },",
            "",
        ]

    lines += ["];", ""]

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))

    print("Wrote %s" % os.path.relpath(OUT, HERE))
    print("  %d clips  ->  %d adventures (one per day)" % (len(files), len(days)))

    if warnings:
        print("\n%d file(s) may not play in a browser:" % len(warnings))
        for name, why in warnings:
            print("  %-40s %s" % (name, why))
        print("\nConvert them with ffmpeg (keeps the originals untouched):")
        print('  cd videos')
        print('  for f in *.MOV *.mov; do ffmpeg -i "$f" -c:v libx264 -crf 22 '
              '-c:a aac -movflags +faststart "${f%.*}.mp4"; done')
        print("\nThen re-run this script.")


if __name__ == "__main__":
    main()
